### ISSUE TITLE
Remove .env file 

### ISSUE THREAD

**Issue by Shreyas15srivatsa** [FYDP-1nil/backend#11]
https://github.com/FYDP-1nil/backend/blob/401bb11e9f4e0ed21eedf41ba46e934496ab36b5/backend/mantle/.env#L1

Why's this in main?

**Comment by madhur4444** [comment]
Done here https://github.com/FYDP-1nil/backend/commit/7a5f3fb233929a6f59fe5e3cae7a2eecf5a22ece
