### ISSUE TITLE
[Bug] Fix "DNS resolution failed" bug

### ISSUE THREAD

**Issue by Shreyas15srivatsa** [FYDP-1nil/backend#12]
After migrating the backend to be hosted using docker containers, grpc is having a hard time to communicate between docker images. More specifically, the `1nil-mantle` docker image can't find the DNS hostname for `1nil-stats`, another docker image. 

```
details = "DNS resolution failed for '1nil-stats':50052: UNKNOWN: Name or service not known"
1nil-mantle    | 	debug_error_string = "UNKNOWN:DNS resolution failed for '1nil-stats':50052: UNKNOWN: Name or service not known {grpc_status:14, created_time:"2023-02-19T17:12:13.780869384+00:00"}"
```

**Comment by Shreyas15srivatsa** [comment]
PR ->  https://github.com/FYDP-1nil/backend/pull/18

**Comment by madhur4444** [comment]
LGTM)
