### ISSUE TITLE
[Streamer] [Bug] Investigate issue with fetching Twitch stream key, API returns 401

### ISSUE THREAD

**Issue by Shreyas15srivatsa** [FYDP-1nil/backend#19]
After updating the Oauth token, the second API GET request fails with 401, please look into this. 

![Image](https://user-images.githubusercontent.com/37994733/219986687-4cc3dc7d-a250-4ff5-a61a-2a4fd0c15e19.png)

Additionally, we are not using Youtube for streaming so please clean the service.py to remove any instance of Youtube. Also, clean up mantle side of things where we check the type of stream and invoke the required function. We can skip this step and always invoke twitch from mantle.

**Comment by madhur4444** [comment]
Fixed here https://github.com/FYDP-1nil/backend/commit/dcd0c12eebd3c6c2ab084563fc8c1b5c6c47ce7a

**Comment by Shreyas15srivatsa** [comment]
Reopened since bug not fixed.
