### ISSUE TITLE
[Mantle] Make the endpoint POST /league/join return the league id instead of a message

### ISSUE THREAD

**Issue by KnotScientific** [FYDP-1nil/backend#28]
Since we are incorporating leagues into our games. We need to pass in what league the game belongs to when a game is first created. Currently the endpoint /league/join returns a success message. It should return the league_id.

![image](https://user-images.githubusercontent.com/29667155/220243315-86df716f-dc94-44ff-a722-2455e68274e7.png)

**Comment by Shreyas15srivatsa** [comment]
![Image](https://user-images.githubusercontent.com/37994733/220266035-196def17-367f-4435-bdde-2cb681c2ccb7.png)

**Comment by Shreyas15srivatsa** [comment]
PR -> https://github.com/FYDP-1nil/backend/pull/31
