### ISSUE TITLE
Update Soccer db schema

### ISSUE THREAD

**Issue by Shreyas15srivatsa** [FYDP-1nil/backend#5]
![Image](https://user-images.githubusercontent.com/37994733/219958332-c45c84f0-f956-4441-99cd-120cbef34667.png)

**Comment by babrar** [comment]
@KnotScientific Same question as [this](https://github.com/FYDP-1nil/backend/issues/6#issuecomment-1437176114)

**Comment by babrar** [comment]
@Shreyas15srivatsa @KnotScientific I kind of hijacked this task because it was relevant to my future tasks. PR -> #35

Let me know what you think of the changes.

**Comment by Shreyas15srivatsa** [comment]
@babrar your PR contains the Postgres DB schema changes, right? There's still changes needed on mantle and stats to fully complete this task, so don't move it to done after the PR has been merged in.

**Comment by babrar** [comment]
> @babrar your PR contains the Postgres DB schema changes, right? There's still changes needed on mantle and stats to fully complete this task, so don't move it to done after the PR has been merged in.

It does contain pg db schema changes. However, there _should_ be no breaking changes. I'm still testing to see if any postman request breaks 1nil as a result of this change.

**Comment by babrar** [comment]
@KnotScientific attaching a sport to a league will cause breaking changes atm --> https://github.com/FYDP-1nil/backend/pull/35#issuecomment-1442066125

**Comment by Shreyas15srivatsa** [comment]
@babrar: I'll checkout your branch and try to implement the code changes needed to make this work.

**Comment by babrar** [comment]
@Shreyas15srivatsa In that case, I have added a couple more changes to finalize the schema. `git pull` before building on it.

**Comment by Shreyas15srivatsa** [comment]
Fixed breaking changes, PR ready for review.

**Comment by Shreyas15srivatsa** [comment]
PR merged in, noice job, men.
